#!/usr/bin/env bash

STATE=$(eww windows | grep osd | awk '{print substr ($0, 0, 1)}')

if [[ $1 == 'close' ]]; then
    # if [[ $STATE == '*' ]]; then eww close osd;
    #  fi
    echo "";
else
    eww update osd="{ \"icon\": \"$1\", \"value\": \"$2\" }"
    if [[ $STATE != '*' ]]; then eww open osd; fi
    if [[ $STATE == '*' ]]; then eww close osd; fi
fi